// <auto-generated />
using System;
using InventoryManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731080000_MoveUnitConversionsToUnits")]
    partial class MoveUnitConversionsToUnits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FactorToBaseUnit")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUnitId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FactorToBaseUnit = 1m,
                            IsActive = true,
                            Name = "Ton"
                        },
                        new
                        {
                            Id = 2,
                            BaseUnitId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FactorToBaseUnit = 1m,
                            IsActive = true,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 3,
                            BaseUnitId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FactorToBaseUnit = 1m,
                            IsActive = true,
                            Name = "Bag"
                        },
                        new
                        {
                            Id = 4,
                            BaseUnitId = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FactorToBaseUnit = 1m,
                            IsActive = true,
                            Name = "Piece"
                        },
                        new
                        {
                            Id = 5,
                            BaseUnitId = 5,
                            CreatedAtUtc = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FactorToBaseUnit = 1m,
                            IsActive = true,
                            Name = "Cubic foot"
                        },
                        new
                        {
                            Id = 6,
                            BaseUnitId = 6,
                            CreatedAtUtc = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FactorToBaseUnit = 1m,
                            IsActive = true,
                            Name = "Cubic meter"
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Unit", b =>
                {
                    b.HasOne("InventoryManagement.Domain.Entities.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");
                });
#pragma warning restore 612, 618
        }
    }
}
