name: .NET CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: inventory_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d inventory_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Packages
        run: dotnet restore InventoryManagement.sln

      - name: Build Solution
        run: dotnet build InventoryManagement.sln --no-restore --configuration Release

      - name: Run Tests
        env:
          INVENTORY_TEST_POSTGRES_ADMIN_CONNECTION: Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=postgres
        run: dotnet test InventoryManagement.sln --no-build --configuration Release
